import type { InventoryLayout } from "../hooks/useInventoryLayout";

// Static pages are generated by preset-maker-storage. This is deliberately
// separate from the API's legacy presets.pvme.io compatibility endpoint.
const configuredBase = import.meta.env.VITE_PRESET_EMBED_BASE_URL
  || "https://pvme.io/preset-maker-storage/embeds/";

export function buildEmbedLink(
  id: string,
  layout: InventoryLayout,
  baseUrl = configuredBase,
): string {
  const base = new URL(baseUrl);
  base.pathname = `${base.pathname.replace(/\/+$/, "")}/`;
  if (base.search || base.hash) throw new Error("Embed base URL must not contain a query or hash");
  const encodedId = encodeURIComponent(id);
  const embed = new URL(
    layout === "4x7" ? `${encodedId}/4x7/` : `${encodedId}/`,
    base,
  );
  // Keep the mode explicit so any redirect from the static embed opens the
  // matching editor arrangement, including the default 7x4 layout.
  embed.searchParams.set("layout", layout);
  return embed.href;
}
